### ISSUE TITLE
[Dumb Question] what does gunicorn start?

### ISSUE THREAD

**Issue by venteto** [bluesky-astronomy/astronomy-feeds#10]
Hi, [I was told](https://github.com/MarshalX/atproto/discussions/243#discussioncomment-8129526) I should look at your repo as an example in trying to make my own feed generators.

I notice you have a commit removing a Flask app, so I was just curious what you actually have gunicorn starting, e.g., what does your gunicorn command(s) look like?

**Comment by emilyhunt** [comment]
Hi!

So the astronomy feed is currently in a bit of flux - I'm splitting it up into multiple services, except I haven't quite finished doing that yet :sweat_smile: so it's a bit weird to look at. If you're starting from scratch, I'd still recommend just using [the default example](https://github.com/MarshalX/bluesky-feed-generator) that MarshalX made for now.

But to answer your original question, the commit removing Flask is because the Flask server is [a separate service](https://github.com/bluesky-astronomy/astrofeed-server). The references to gunicorn in this repo are things I should have removed when that happened... the Flask server repo has an exact version of the Flask app + gunicorn commands used at the moment in production.

Maybe try using a copy of my [gunicorn config file](https://github.com/bluesky-astronomy/astrofeed-server/blob/main/gunicorn_config.py) from the Flask service (except set workers=1)? For your firehose, the gunicorn file affects how many copies of the Flask server are running, but each server *also creates a firehose instance* at startup - those are probably clashing. You should only need a single thread for the Flask server unless you're getting an insane number of queries.

To change the number of workers that the *firehose* uses, you need to edit the code elsewhere - it looks like [your data_stream.py is single-process](https://github.com/venteto/bsky-feedgen/blob/main/server/data_stream.py). On the other hand, for my feed, the firehose is [in this file](https://github.com/bluesky-astronomy/astronomy-feeds/blob/main/server/firehose.py) and uses an additional worker process to process posts (I use a single worker as AWS - where the feed is hosted - doesn't support using multiprocessing.Queue). I haven't had any issues with posts being missed for months, but I also think a single-process firehose (as in the default example & your code) should be fine.

If you really need speed in the firehose, there's also a multi-process example that uses [a Queue and a Pool](https://github.com/MarshalX/atproto/blob/main/examples/firehose/process_commits.py) - though realistically, I doubt that that's the issue.

I hope that helps!

**Comment by venteto** [comment]
Thanks for your input
